version: "3.8"

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  producer:
    build:
      context: .
      dockerfile: Dockerfile_producer
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./producer.py:/app/producer.py
      - ./utils:/app/utils
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      POLL_INTERVAL: ${POLL_INTERVAL}

  consumer:
    build:
      context: .
      dockerfile: Dockerfile_consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./consumer.py:/app/consumer.py
      - ./utils:/app/utils
    environment:
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      POLL_INTERVAL: ${POLL_INTERVAL}
